"""totp and login rate limit

Revision ID: bf4c51bade67
Revises: 6131caf88720
Create Date: 2026-08-23 12:11:21.682517
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'bf4c51bade67'
down_revision = '6131caf88720'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_login_attempts', schema=None) as batch_op:
        batch_op.create_index('ix_login_attempts_ip_at', ['ip', 'at'], unique=False)
        batch_op.create_index('ix_login_attempts_username_at', ['username', 'at'], unique=False)

    op.create_table('auth_recovery_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auth_recovery_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_recovery_codes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('auth_recovery_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_recovery_codes_user_id'))

    op.drop_table('auth_recovery_codes')
    with op.batch_alter_table('auth_login_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_login_attempts_username_at')
        batch_op.drop_index('ix_login_attempts_ip_at')

    op.drop_table('auth_login_attempts')
    # ### end Alembic commands ###
