"""servers control audit log

Revision ID: ea7336942647
Revises: bf4c51bade67
Create Date: 2026-08-23 21:38:47.170152
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ea7336942647'
down_revision = 'bf4c51bade67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servers_control_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('container_id', sa.String(length=64), nullable=False),
    sa.Column('container_name', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('servers_control_log', schema=None) as batch_op:
        batch_op.create_index('ix_servers_control_log_at', ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_servers_control_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servers_control_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_servers_control_log_user_id'))
        batch_op.drop_index('ix_servers_control_log_at')

    op.drop_table('servers_control_log')
    # ### end Alembic commands ###
